# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "OFF")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "OFF")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "OFF")
SET(CPACK_BINARY_PACKAGEMAKER "ON")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TGZ;TBZ2;ZIP")
SET(CPACK_IGNORE_FILES "\\.#;/#;.*~;/\\.git;/\\.svn;/Users/mikest/github/othercam/OpenMesh-2.0/cmake;Makefile;Makefile\\..*;\\.moc\\.cpp$;CMakeCache.txt;CMakeFiles;/.*_(32|64)_Debug/;/.*_(32|64)_Release/;/MacOS;/WIN;/tmp/;/.*\\.kdevelop;/.*\\.kdevses;/ACG/lib/;/ACG/include/")
SET(CPACK_INSTALLED_DIRECTORIES "/Users/mikest/github/othercam/OpenMesh-2.0;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/Users/mikest/github/othercam/OpenMesh-2.0/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "OpenMesh 2.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "OpenMesh 2.0")
SET(CPACK_OUTPUT_CONFIG_FILE "/Users/mikest/github/othercam/OpenMesh-2.0/cmake/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/Applications/CMake 2.8-11.app/Contents/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OpenMesh")
SET(CPACK_PACKAGE_FILE_NAME "OpenMesh-2.0")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "OpenMesh 2.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "OpenMesh")
SET(CPACK_PACKAGE_NAME "OpenMesh")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "ACG")
SET(CPACK_PACKAGE_VERSION "2.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "2")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "/Applications/CMake 2.8-11.app/Contents/share/cmake-2.8/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/Applications/CMake 2.8-11.app/Contents/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/Applications/CMake 2.8-11.app/Contents/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "\\.#;/#;.*~;/\\.git;/\\.svn;/Users/mikest/github/othercam/OpenMesh-2.0/cmake;Makefile;Makefile\\..*;\\.moc\\.cpp$;CMakeCache.txt;CMakeFiles;/.*_(32|64)_Debug/;/.*_(32|64)_Release/;/MacOS;/WIN;/tmp/;/.*\\.kdevelop;/.*\\.kdevses;/ACG/lib/;/ACG/include/")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/mikest/github/othercam/OpenMesh-2.0;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/mikest/github/othercam/OpenMesh-2.0/cmake/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "OpenMesh-2.0")
SET(CPACK_SOURCE_STRIP_FILES "")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Darwin")
SET(CPACK_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
